# Generated by Django 5.2.6 on 2025-11-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Panaderia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='receta',
            options={'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
